const ITEM_TYPES = {
	LOAD_ITEMS: 'LOAD_ITEMS',
	LOAD_ITEMS_SUCCESS: 'LOAD_ITEMS_SUCCESS',
	LOAD_ITEMS_ERROR: 'LOAD_ITEMS_ERROR',
	REQUEST_CREATE_ITEM: 'REQUEST_CREATE_ITEM',
	CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
	CREATE_ITEMS_ERROR: 'CREATE_ITEMS_ERROR',
	GET_ITEM: 'GET_ITEM',
	GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
	GET_ITEM_ERROR: 'GET_ITEM_ERROR',
	EDIT_ITEM: 'EDIT_ITEM',
	EDIT_ITEM_SUCCESS: 'EDIT_ITEM_SUCCESS',
	EDIT_ITEM_ERROR: 'EDIT_ITEM_ERROR',
	DELETE_ITEM: 'DELETE_ITEM',
	DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
	DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',
	RESET_ITEM: 'RESET_ITEM',
};

export default ITEM_TYPES;

